version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/sample_app
permissions:
  - object: /var/www/sample_app
    owner: apache
    group: apache
    pattern: "*"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: sample_app_scripts/arrange-deployment-folders.sh
      runas: root
  AfterInstall:
    - location: sample_app_scripts/db-config.sh
      runas: apache
    - location: sample_app_scripts/install-gems.sh
      runas: apache
    - location: sample_app_scripts/compile-assets.sh
      runas: apache
    - location: sample_app_scripts/run-db-migrations.sh
      runas: apache

  ApplicationStart:
    - location: sample_app_scripts/finish-installation.sh
      runas: root
